test:
	docker-compose run --rm phaudi noverify -version
	docker-compose run --rm phaudi phploc --version
	docker-compose run --rm phaudi pdepend --version
	docker-compose run --rm phaudi phan --version
	docker-compose run --rm phaudi phpmd --version
	docker-compose run --rm phaudi phpcs --version
	docker-compose run --rm phaudi phpcbf --version
	docker-compose run --rm phaudi phpcpd --version
	docker-compose run --rm phaudi phpdcd --version
	docker-compose run --rm phaudi phpcf --version
	docker-compose run --rm phaudi phpmetrics --version
	docker-compose run --rm phaudi php-cs-fixer --version
	docker-compose run --rm phaudi phpstan --version
	docker-compose run --rm phaudi yaml-linter --version
	docker-compose run --rm phaudi security-checker --version

clean:
